## Installing Dependacies

In [ ]:
!pip install rouge-score
!pip install accelerate -U

Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: absl-py in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from rouge-score) (2.1.0)
Collecting nltk (from rouge-score)
  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: numpy in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from rouge-score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from rouge-score) (1.17.0)
Collecting click (from nltk->rouge-score)
  Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: joblib in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from nltk->rouge-score) (1.4.2)
Collecting regex>=2021.8.3 (from nltk->rouge-score)
  Using cached regex-2024.11.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk->rouge-score)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from click->nltk->rouge-score) (0.4.6)
Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)
Using cached regex-2024.11.6-cp312-cp312-win_amd64.whl (273 kB)
Downloading click-8.1.8-py3-none-any.whl (98 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py): started
  Building wheel for rouge-score (setup.py): finished with status 'done'
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=25025 sha256=c60d2dd0d6deaad7775a88e128473a4ca1da6b56ea345e890641e283348a4e5e
  Stored in directory: c:\users\va185069\appdata\local\pip\cache\wheels\85\9d\af\01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: tqdm, regex, click, nltk, rouge-score
Successfully installed click-8.1.8 nltk-3.9.1 regex-2024.11.6 rouge-score-0.1.2 tqdm-4.67.1

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting accelerate
  Downloading accelerate-1.3.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy<3.0.0,>=1.17 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from accelerate) (24.2)
Requirement already satisfied: psutil in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from accelerate) (6.1.0)
Collecting pyyaml (from accelerate)
  Using cached PyYAML-6.0.2-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
Collecting torch>=2.0.0 (from accelerate)
  Downloading torch-2.6.0-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting huggingface-hub>=0.21.0 (from accelerate)
  Downloading huggingface_hub-0.28.1-py3-none-any.whl.metadata (13 kB)
Collecting safetensors>=0.4.3 (from accelerate)
  Downloading safetensors-0.5.2-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Collecting filelock (from huggingface-hub>=0.21.0->accelerate)
  Downloading filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.21.0->accelerate)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: requests in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from huggingface-hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from huggingface-hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from huggingface-hub>=0.21.0->accelerate) (4.12.2)
Collecting networkx (from torch>=2.0.0->accelerate)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch>=2.0.0->accelerate)
  Downloading jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: setuptools in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from torch>=2.0.0->accelerate) (75.8.0)
Collecting sympy==1.13.1 (from torch>=2.0.0->accelerate)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch>=2.0.0->accelerate)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2024.12.14)
Downloading accelerate-1.3.0-py3-none-any.whl (336 kB)
Downloading huggingface_hub-0.28.1-py3-none-any.whl (464 kB)
Using cached PyYAML-6.0.2-cp312-cp312-win_amd64.whl (156 kB)
Downloading safetensors-0.5.2-cp38-abi3-win_amd64.whl (303 kB)
Downloading torch-2.6.0-cp312-cp312-win_amd64.whl (204.1 MB)
   ---------------------------------------- 0.0/204.1 MB ? eta -:--:--
   ---------------------------------------- 1.8/204.1 MB 9.1 MB/s eta 0:00:23
    --------------------------------------- 2.9/204.1 MB 8.0 MB/s eta 0:00:26
    --------------------------------------- 3.1/204.1 MB 6.4 MB/s eta 0:00:32
    --------------------------------------- 3.7/204.1 MB 4.5 MB/s eta 0:00:45
    --------------------------------------- 3.7/204.1 MB 4.5 MB/s eta 0:00:45
    --------------------------------------- 4.2/204.1 MB 3.3 MB/s eta 0:01:02
    --------------------------------------- 5.0/204.1 MB 3.4 MB/s eta 0:00:59
   - -------------------------------------- 6.0/204.1 MB 3.6 MB/s eta 0:00:55
   - -------------------------------------- 7.3/204.1 MB 3.9 MB/s eta 0:00:51
   - -------------------------------------- 8.7/204.1 MB 4.1 MB/s eta 0:00:48
   - -------------------------------------- 9.7/204.1 MB 4.3 MB/s eta 0:00:46
   -- ------------------------------------- 10.7/204.1 MB 4.3 MB/s eta 0:00:45
   -- ------------------------------------- 11.5/204.1 MB 4.3 MB/s eta 0:00:45
   -- ------------------------------------- 11.5/204.1 MB 4.3 MB/s eta 0:00:45
   -- ------------------------------------- 11.5/204.1 MB 4.3 MB/s eta 0:00:45
   -- ------------------------------------- 11.8/204.1 MB 3.6 MB/s eta 0:00:54
   -- ------------------------------------- 11.8/204.1 MB 3.6 MB/s eta 0:00:54
   -- ------------------------------------- 11.8/204.1 MB 3.6 MB/s eta 0:00:54
   -- ------------------------------------- 12.1/204.1 MB 3.0 MB/s eta 0:01:04
   -- ------------------------------------- 12.1/204.1 MB 3.0 MB/s eta 0:01:04
   -- ------------------------------------- 12.1/204.1 MB 3.0 MB/s eta 0:01:04
   -- ------------------------------------- 12.3/204.1 MB 2.8 MB/s eta 0:01:10
   -- ------------------------------------- 12.6/204.1 MB 2.6 MB/s eta 0:01:14
   -- ------------------------------------- 12.6/204.1 MB 2.6 MB/s eta 0:01:14
   -- ------------------------------------- 12.6/204.1 MB 2.6 MB/s eta 0:01:14
   -- ------------------------------------- 12.8/204.1 MB 2.4 MB/s eta 0:01:20
   -- ------------------------------------- 13.1/204.1 MB 2.3 MB/s eta 0:01:22
   -- ------------------------------------- 13.6/204.1 MB 2.3 MB/s eta 0:01:24
   -- ------------------------------------- 13.9/204.1 MB 2.3 MB/s eta 0:01:24
   -- ------------------------------------- 14.4/204.1 MB 2.3 MB/s eta 0:01:24
   -- ------------------------------------- 14.7/204.1 MB 2.3 MB/s eta 0:01:24
   -- ------------------------------------- 15.2/204.1 MB 2.3 MB/s eta 0:01:24
   --- ------------------------------------ 15.7/204.1 MB 2.3 MB/s eta 0:01:24
   --- ------------------------------------ 16.3/204.1 MB 2.3 MB/s eta 0:01:23
   --- ------------------------------------ 16.8/204.1 MB 2.3 MB/s eta 0:01:23
   --- ------------------------------------ 17.3/204.1 MB 2.3 MB/s eta 0:01:22
   --- ------------------------------------ 17.8/204.1 MB 2.3 MB/s eta 0:01:22
   --- ------------------------------------ 18.4/204.1 MB 2.3 MB/s eta 0:01:21
   --- ------------------------------------ 19.1/204.1 MB 2.3 MB/s eta 0:01:21
   --- ------------------------------------ 19.7/204.1 MB 2.3 MB/s eta 0:01:20
   --- ------------------------------------ 20.2/204.1 MB 2.3 MB/s eta 0:01:19
   ---- ----------------------------------- 21.0/204.1 MB 2.4 MB/s eta 0:01:18
   ---- ----------------------------------- 21.8/204.1 MB 2.4 MB/s eta 0:01:17
   ---- ----------------------------------- 21.8/204.1 MB 2.4 MB/s eta 0:01:17
   ---- ----------------------------------- 22.0/204.1 MB 2.3 MB/s eta 0:01:19
   ---- ----------------------------------- 22.0/204.1 MB 2.3 MB/s eta 0:01:19
   ---- ----------------------------------- 22.0/204.1 MB 2.3 MB/s eta 0:01:19
   ---- ----------------------------------- 22.0/204.1 MB 2.3 MB/s eta 0:01:19
   ---- ----------------------------------- 22.0/204.1 MB 2.3 MB/s eta 0:01:19
   ---- ----------------------------------- 22.0/204.1 MB 2.3 MB/s eta 0:01:19
   ---- ----------------------------------- 22.3/204.1 MB 2.1 MB/s eta 0:01:27
   ---- ----------------------------------- 22.3/204.1 MB 2.1 MB/s eta 0:01:27
   ---- ----------------------------------- 22.5/204.1 MB 2.0 MB/s eta 0:01:30
   ---- ----------------------------------- 22.5/204.1 MB 2.0 MB/s eta 0:01:30
   ---- ----------------------------------- 22.8/204.1 MB 2.0 MB/s eta 0:01:33
   ---- ----------------------------------- 23.1/204.1 MB 1.9 MB/s eta 0:01:33
   ---- ----------------------------------- 23.3/204.1 MB 1.9 MB/s eta 0:01:34
   ---- ----------------------------------- 23.6/204.1 MB 1.9 MB/s eta 0:01:34
   ---- ----------------------------------- 23.9/204.1 MB 1.9 MB/s eta 0:01:35
   ---- ----------------------------------- 24.1/204.1 MB 1.9 MB/s eta 0:01:35
   ---- ----------------------------------- 24.6/204.1 MB 1.9 MB/s eta 0:01:35
   ---- ----------------------------------- 24.9/204.1 MB 1.9 MB/s eta 0:01:35
   ---- ----------------------------------- 25.4/204.1 MB 1.9 MB/s eta 0:01:34
   ----- ---------------------------------- 26.0/204.1 MB 1.9 MB/s eta 0:01:33
   ----- ---------------------------------- 26.5/204.1 MB 1.9 MB/s eta 0:01:33
   ----- ---------------------------------- 27.0/204.1 MB 1.9 MB/s eta 0:01:32
   ----- ---------------------------------- 27.5/204.1 MB 1.9 MB/s eta 0:01:32
   ----- ---------------------------------- 28.0/204.1 MB 1.9 MB/s eta 0:01:31
   ----- ---------------------------------- 28.3/204.1 MB 2.0 MB/s eta 0:01:31
   ----- ---------------------------------- 28.8/204.1 MB 2.0 MB/s eta 0:01:30
   ----- ---------------------------------- 29.4/204.1 MB 2.0 MB/s eta 0:01:30
   ----- ---------------------------------- 29.6/204.1 MB 2.0 MB/s eta 0:01:30
   ----- ---------------------------------- 30.1/204.1 MB 2.0 MB/s eta 0:01:30
   ------ --------------------------------- 30.7/204.1 MB 2.0 MB/s eta 0:01:29
   ------ --------------------------------- 30.9/204.1 MB 2.0 MB/s eta 0:01:29
   ------ --------------------------------- 31.5/204.1 MB 2.0 MB/s eta 0:01:29
   ------ --------------------------------- 32.0/204.1 MB 2.0 MB/s eta 0:01:28
   ------ --------------------------------- 32.5/204.1 MB 2.0 MB/s eta 0:01:28
   ------ --------------------------------- 33.0/204.1 MB 2.0 MB/s eta 0:01:27
   ------ --------------------------------- 33.8/204.1 MB 2.0 MB/s eta 0:01:26
   ------ --------------------------------- 34.3/204.1 MB 2.0 MB/s eta 0:01:25
   ------ --------------------------------- 34.9/204.1 MB 2.0 MB/s eta 0:01:25
   ------ --------------------------------- 34.9/204.1 MB 2.0 MB/s eta 0:01:25
   ------ --------------------------------- 35.1/204.1 MB 2.0 MB/s eta 0:01:25
   ------ --------------------------------- 35.1/204.1 MB 2.0 MB/s eta 0:01:25
   ------ --------------------------------- 35.7/204.1 MB 2.0 MB/s eta 0:01:26
   ------- -------------------------------- 35.9/204.1 MB 2.0 MB/s eta 0:01:26
   ------- -------------------------------- 36.4/204.1 MB 2.0 MB/s eta 0:01:26
   ------- -------------------------------- 37.0/204.1 MB 2.0 MB/s eta 0:01:26
   ------- -------------------------------- 37.2/204.1 MB 2.0 MB/s eta 0:01:26
   ------- -------------------------------- 37.7/204.1 MB 2.0 MB/s eta 0:01:25
   ------- -------------------------------- 38.0/204.1 MB 2.0 MB/s eta 0:01:25
   ------- -------------------------------- 38.8/204.1 MB 2.0 MB/s eta 0:01:25
   ------- -------------------------------- 39.1/204.1 MB 2.0 MB/s eta 0:01:24
   ------- -------------------------------- 39.8/204.1 MB 2.0 MB/s eta 0:01:24
   ------- -------------------------------- 40.4/204.1 MB 2.0 MB/s eta 0:01:23
   -------- ------------------------------- 40.9/204.1 MB 2.0 MB/s eta 0:01:22
   -------- ------------------------------- 41.4/204.1 MB 2.0 MB/s eta 0:01:22
   -------- ------------------------------- 41.9/204.1 MB 2.0 MB/s eta 0:01:21
   -------- ------------------------------- 42.5/204.1 MB 2.0 MB/s eta 0:01:21
   -------- ------------------------------- 43.0/204.1 MB 2.0 MB/s eta 0:01:20
   -------- ------------------------------- 43.0/204.1 MB 2.0 MB/s eta 0:01:20
   -------- ------------------------------- 43.5/204.1 MB 2.0 MB/s eta 0:01:21
   -------- ------------------------------- 44.0/204.1 MB 2.0 MB/s eta 0:01:20
   -------- ------------------------------- 44.3/204.1 MB 2.0 MB/s eta 0:01:21
   -------- ------------------------------- 44.6/204.1 MB 2.0 MB/s eta 0:01:20
   -------- ------------------------------- 45.1/204.1 MB 2.0 MB/s eta 0:01:20
   -------- ------------------------------- 45.6/204.1 MB 2.0 MB/s eta 0:01:20
   --------- ------------------------------ 46.1/204.1 MB 2.0 MB/s eta 0:01:19
   --------- ------------------------------ 46.7/204.1 MB 2.0 MB/s eta 0:01:19
   --------- ------------------------------ 47.2/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 47.7/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 47.7/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 48.2/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 48.8/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 49.3/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 49.5/204.1 MB 2.0 MB/s eta 0:01:17
   --------- ------------------------------ 49.5/204.1 MB 2.0 MB/s eta 0:01:17
   --------- ------------------------------ 50.1/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 50.3/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 50.3/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 50.6/204.1 MB 2.0 MB/s eta 0:01:19
   --------- ------------------------------ 50.6/204.1 MB 2.0 MB/s eta 0:01:19
   --------- ------------------------------ 50.9/204.1 MB 1.9 MB/s eta 0:01:19
   ---------- ----------------------------- 51.1/204.1 MB 1.9 MB/s eta 0:01:19
   ---------- ----------------------------- 51.4/204.1 MB 1.9 MB/s eta 0:01:20
   ---------- ----------------------------- 51.4/204.1 MB 1.9 MB/s eta 0:01:20
   ---------- ----------------------------- 51.4/204.1 MB 1.9 MB/s eta 0:01:20
   ---------- ----------------------------- 51.6/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 51.6/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 51.9/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 52.2/204.1 MB 1.9 MB/s eta 0:01:22
   ---------- ----------------------------- 52.4/204.1 MB 1.9 MB/s eta 0:01:22
   ---------- ----------------------------- 52.7/204.1 MB 1.9 MB/s eta 0:01:22
   ---------- ----------------------------- 53.0/204.1 MB 1.9 MB/s eta 0:01:22
   ---------- ----------------------------- 53.5/204.1 MB 1.9 MB/s eta 0:01:22
   ---------- ----------------------------- 54.0/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 54.3/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 54.5/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 54.5/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 54.5/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 54.5/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 54.5/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 54.5/204.1 MB 1.9 MB/s eta 0:01:21
   ---------- ----------------------------- 54.8/204.1 MB 1.7 MB/s eta 0:01:27
   ---------- ----------------------------- 54.8/204.1 MB 1.7 MB/s eta 0:01:27
   ---------- ----------------------------- 54.8/204.1 MB 1.7 MB/s eta 0:01:27
   ---------- ----------------------------- 54.8/204.1 MB 1.7 MB/s eta 0:01:27
   ---------- ----------------------------- 55.1/204.1 MB 1.7 MB/s eta 0:01:30
   ---------- ----------------------------- 55.1/204.1 MB 1.7 MB/s eta 0:01:30
   ---------- ----------------------------- 55.1/204.1 MB 1.7 MB/s eta 0:01:30
   ---------- ----------------------------- 55.3/204.1 MB 1.5 MB/s eta 0:01:37
   ---------- ----------------------------- 55.3/204.1 MB 1.5 MB/s eta 0:01:37
   ---------- ----------------------------- 55.6/204.1 MB 1.5 MB/s eta 0:01:40
   ---------- ----------------------------- 55.8/204.1 MB 1.5 MB/s eta 0:01:40
   ---------- ----------------------------- 55.8/204.1 MB 1.5 MB/s eta 0:01:40
   ----------- ---------------------------- 56.4/204.1 MB 1.5 MB/s eta 0:01:40
   ----------- ---------------------------- 56.6/204.1 MB 1.5 MB/s eta 0:01:38
   ----------- ---------------------------- 56.9/204.1 MB 1.5 MB/s eta 0:01:38
   ----------- ---------------------------- 57.1/204.1 MB 1.5 MB/s eta 0:01:38
   ----------- ---------------------------- 57.7/204.1 MB 1.5 MB/s eta 0:01:36
   ----------- ---------------------------- 58.2/204.1 MB 1.5 MB/s eta 0:01:35
   ----------- ---------------------------- 58.5/204.1 MB 1.5 MB/s eta 0:01:35
   ----------- ---------------------------- 59.0/204.1 MB 1.6 MB/s eta 0:01:34
   ----------- ---------------------------- 59.5/204.1 MB 1.6 MB/s eta 0:01:32
   ----------- ---------------------------- 60.0/204.1 MB 1.6 MB/s eta 0:01:31
   ----------- ---------------------------- 60.6/204.1 MB 1.6 MB/s eta 0:01:31
   ------------ --------------------------- 61.3/204.1 MB 1.6 MB/s eta 0:01:29
   ------------ --------------------------- 61.9/204.1 MB 1.6 MB/s eta 0:01:28
   ------------ --------------------------- 62.7/204.1 MB 1.6 MB/s eta 0:01:27
   ------------ --------------------------- 63.4/204.1 MB 1.6 MB/s eta 0:01:26
   ------------ --------------------------- 64.2/204.1 MB 1.7 MB/s eta 0:01:25
   ------------ --------------------------- 65.0/204.1 MB 1.7 MB/s eta 0:01:24
   ------------ --------------------------- 65.8/204.1 MB 1.7 MB/s eta 0:01:23
   ------------ --------------------------- 66.3/204.1 MB 1.7 MB/s eta 0:01:23
   ------------- -------------------------- 67.1/204.1 MB 1.7 MB/s eta 0:01:22
   ------------- -------------------------- 67.9/204.1 MB 1.7 MB/s eta 0:01:21
   ------------- -------------------------- 68.7/204.1 MB 1.7 MB/s eta 0:01:20
   ------------- -------------------------- 69.5/204.1 MB 1.7 MB/s eta 0:01:19
   ------------- -------------------------- 70.5/204.1 MB 1.7 MB/s eta 0:01:18
   ------------- -------------------------- 71.3/204.1 MB 1.7 MB/s eta 0:01:17
   -------------- ------------------------- 72.4/204.1 MB 1.7 MB/s eta 0:01:16
   -------------- ------------------------- 73.1/204.1 MB 1.7 MB/s eta 0:01:15
   -------------- ------------------------- 73.7/204.1 MB 1.7 MB/s eta 0:01:15
   -------------- ------------------------- 74.2/204.1 MB 1.8 MB/s eta 0:01:14
   -------------- ------------------------- 75.2/204.1 MB 1.8 MB/s eta 0:01:13
   -------------- ------------------------- 76.3/204.1 MB 1.9 MB/s eta 0:01:09
   --------------- ------------------------ 77.3/204.1 MB 1.9 MB/s eta 0:01:08
   --------------- ------------------------ 78.1/204.1 MB 1.9 MB/s eta 0:01:07
   --------------- ------------------------ 79.2/204.1 MB 1.9 MB/s eta 0:01:06
   --------------- ------------------------ 80.0/204.1 MB 1.9 MB/s eta 0:01:05
   --------------- ------------------------ 80.7/204.1 MB 2.0 MB/s eta 0:01:03
   --------------- ------------------------ 81.3/204.1 MB 2.0 MB/s eta 0:01:03
   ---------------- ----------------------- 82.1/204.1 MB 2.0 MB/s eta 0:01:01
   ---------------- ----------------------- 83.1/204.1 MB 2.0 MB/s eta 0:01:00
   ---------------- ----------------------- 83.9/204.1 MB 2.0 MB/s eta 0:01:00
   ---------------- ----------------------- 84.9/204.1 MB 2.1 MB/s eta 0:00:58
   ---------------- ----------------------- 85.7/204.1 MB 2.1 MB/s eta 0:00:57
   ---------------- ----------------------- 86.5/204.1 MB 2.1 MB/s eta 0:00:57
   ----------------- ---------------------- 87.3/204.1 MB 2.1 MB/s eta 0:00:56
   ----------------- ---------------------- 88.1/204.1 MB 2.1 MB/s eta 0:00:55
   ----------------- ---------------------- 89.1/204.1 MB 2.2 MB/s eta 0:00:54
   ----------------- ---------------------- 89.9/204.1 MB 2.2 MB/s eta 0:00:53
   ----------------- ---------------------- 90.7/204.1 MB 2.2 MB/s eta 0:00:53
   ------------------ --------------------- 92.0/204.1 MB 2.2 MB/s eta 0:00:51
   ------------------ --------------------- 93.1/204.1 MB 2.2 MB/s eta 0:00:51

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting gradio
  Downloading gradio-5.14.0-py3-none-any.whl.metadata (16 kB)
Collecting aiofiles<24.0,>=22.0 (from gradio)
  Downloading aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Collecting anyio<5.0,>=3.0 (from gradio)
  Downloading anyio-4.8.0-py3-none-any.whl.metadata (4.6 kB)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.115.8-py3-none-any.whl.metadata (27 kB)
Collecting ffmpy (from gradio)
  Downloading ffmpy-0.5.0-py3-none-any.whl.metadata (3.0 kB)
Collecting gradio-client==1.7.0 (from gradio)
  Downloading gradio_client-1.7.0-py3-none-any.whl.metadata (7.1 kB)
Collecting httpx>=0.24.1 (from gradio)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: huggingface-hub>=0.25.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from gradio) (0.28.1)
Requirement already satisfied: jinja2<4.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from gradio) (3.1.5)
Collecting markupsafe~=2.0 (from gradio)
  Using cached MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from gradio) (2.0.2)
Collecting orjson~=3.0 (from gradio)
  Downloading orjson-3.10.15-cp312-cp312-win_amd64.whl.metadata (42 kB)
Requirement already satisfied: packaging in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from gradio) (2.2.3)
Requirement already satisfied: pillow<12.0,>=8.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from gradio) (11.0.0)
Collecting pydantic>=2.0 (from gradio)
  Downloading pydantic-2.10.6-py3-none-any.whl.metadata (30 kB)
Collecting pydub (from gradio)
  Using cached pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart>=0.0.18 (from gradio)
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from gradio) (6.0.2)
Collecting ruff>=0.9.3 (from gradio)
  Downloading ruff-0.9.4-py3-none-win_amd64.whl.metadata (26 kB)
Collecting safehttpx<0.2.0,>=0.1.6 (from gradio)
  Downloading safehttpx-0.1.6-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio)
  Downloading starlette-0.45.3-py3-none-any.whl.metadata (6.3 kB)
Collecting tomlkit<0.14.0,>=0.12.0 (from gradio)
  Downloading tomlkit-0.13.2-py3-none-any.whl.metadata (2.7 kB)
Collecting typer<1.0,>=0.12 (from gradio)
  Downloading typer-0.15.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: typing-extensions~=4.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from gradio) (4.12.2)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: fsspec in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from gradio-client==1.7.0->gradio) (2024.12.0)
Collecting websockets<15.0,>=10.0 (from gradio-client==1.7.0->gradio)
  Downloading websockets-14.2-cp312-cp312-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: idna>=2.8 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Collecting sniffio>=1.1 (from anyio<5.0,>=3.0->gradio)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: certifi in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from httpx>=0.24.1->gradio) (2024.12.14)
Collecting httpcore==1.* (from httpx>=0.24.1->gradio)
  Downloading httpcore-1.0.7-py3-none-any.whl.metadata (21 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.24.1->gradio)
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: filelock in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from huggingface-hub>=0.25.1->gradio) (3.17.0)
Requirement already satisfied: requests in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from huggingface-hub>=0.25.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from huggingface-hub>=0.25.1->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Collecting annotated-types>=0.6.0 (from pydantic>=2.0->gradio)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.27.2 (from pydantic>=2.0->gradio)
  Downloading pydantic_core-2.27.2-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: click>=8.0.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from typer<1.0,>=0.12->gradio) (8.1.8)
Collecting shellingham>=1.3.0 (from typer<1.0,>=0.12->gradio)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=10.11.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: colorama in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from click>=8.0.0->typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->huggingface-hub>=0.25.1->gradio) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->huggingface-hub>=0.25.1->gradio) (2.3.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading gradio-5.14.0-py3-none-any.whl (57.7 MB)
   ---------------------------------------- 0.0/57.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/57.7 MB 2.8 MB/s eta 0:00:21
   - -------------------------------------- 1.8/57.7 MB 5.6 MB/s eta 0:00:11
   -- ------------------------------------- 3.4/57.7 MB 6.5 MB/s eta 0:00:09
   -- ------------------------------------- 4.2/57.7 MB 6.0 MB/s eta 0:00:09
   --- ------------------------------------ 5.8/57.7 MB 6.0 MB/s eta 0:00:09
   ---- ----------------------------------- 6.0/57.7 MB 6.0 MB/s eta 0:00:09
   ---- ----------------------------------- 6.8/57.7 MB 5.7 MB/s eta 0:00:09
   ----- ---------------------------------- 7.3/57.7 MB 4.8 MB/s eta 0:00:11
   ------ --------------------------------- 8.9/57.7 MB 4.9 MB/s eta 0:00:10
   ------ --------------------------------- 10.0/57.7 MB 5.1 MB/s eta 0:00:10
   ------- -------------------------------- 11.3/57.7 MB 5.1 MB/s eta 0:00:10
   -------- ------------------------------- 12.6/57.7 MB 5.3 MB/s eta 0:00:09
   --------- ------------------------------ 13.4/57.7 MB 5.2 MB/s eta 0:00:09
   --------- ------------------------------ 13.6/57.7 MB 5.1 MB/s eta 0:00:09
   --------- ------------------------------ 13.6/57.7 MB 5.1 MB/s eta 0:00:09
   --------- ------------------------------ 13.9/57.7 MB 4.4 MB/s eta 0:00:10
   --------- ------------------------------ 13.9/57.7 MB 4.4 MB/s eta 0:00:10
   --------- ------------------------------ 13.9/57.7 MB 4.4 MB/s eta 0:00:10
   --------- ------------------------------ 14.2/57.7 MB 3.7 MB/s eta 0:00:12
   --------- ------------------------------ 14.2/57.7 MB 3.7 MB/s eta 0:00:12
   --------- ------------------------------ 14.4/57.7 MB 3.3 MB/s eta 0:00:13
   --------- ------------------------------ 14.4/57.7 MB 3.3 MB/s eta 0:00:13
   --------- ------------------------------ 14.4/57.7 MB 3.3 MB/s eta 0:00:13
   --------- ------------------------------ 14.4/57.7 MB 3.3 MB/s eta 0:00:13
   ---------- ----------------------------- 14.7/57.7 MB 2.9 MB/s eta 0:00:16
   ---------- ----------------------------- 14.7/57.7 MB 2.9 MB/s eta 0:00:16
   ---------- ----------------------------- 14.7/57.7 MB 2.9 MB/s eta 0:00:16
   ---------- ----------------------------- 14.9/57.7 MB 2.7 MB/s eta 0:00:17
   ---------- ----------------------------- 15.2/57.7 MB 2.6 MB/s eta 0:00:17
   ---------- ----------------------------- 15.5/57.7 MB 2.5 MB/s eta 0:00:17
   ---------- ----------------------------- 15.7/57.7 MB 2.5 MB/s eta 0:00:17
   ----------- ---------------------------- 16.0/57.7 MB 2.4 MB/s eta 0:00:18
   ----------- ---------------------------- 16.3/57.7 MB 2.4 MB/s eta 0:00:18
   ----------- ---------------------------- 16.5/57.7 MB 2.4 MB/s eta 0:00:18
   ----------- ---------------------------- 17.0/57.7 MB 2.4 MB/s eta 0:00:18
   ----------- ---------------------------- 17.3/57.7 MB 2.3 MB/s eta 0:00:18
   ------------ --------------------------- 17.8/57.7 MB 2.3 MB/s eta 0:00:18
   ------------ --------------------------- 18.1/57.7 MB 2.3 MB/s eta 0:00:18
   ------------ --------------------------- 18.6/57.7 MB 2.3 MB/s eta 0:00:17
   ------------- -------------------------- 18.9/57.7 MB 2.3 MB/s eta 0:00:17
   ------------- -------------------------- 19.7/57.7 MB 2.3 MB/s eta 0:00:17
   ------------- -------------------------- 20.2/57.7 MB 2.3 MB/s eta 0:00:17
   -------------- ------------------------- 20.7/57.7 MB 2.3 MB/s eta 0:00:16
   -------------- ------------------------- 21.2/57.7 MB 2.3 MB/s eta 0:00:16
   --------------- ------------------------ 22.0/57.7 MB 2.4 MB/s eta 0:00:16
   --------------- ------------------------ 22.5/57.7 MB 2.4 MB/s eta 0:00:15
   --------------- ------------------------ 23.1/57.7 MB 2.4 MB/s eta 0:00:15
   ---------------- ----------------------- 23.9/57.7 MB 2.4 MB/s eta 0:00:15
   ---------------- ----------------------- 24.4/57.7 MB 2.4 MB/s eta 0:00:14
   ----------------- ---------------------- 24.6/57.7 MB 2.4 MB/s eta 0:00:14
   ----------------- ---------------------- 25.4/57.7 MB 2.4 MB/s eta 0:00:14
   ------------------ --------------------- 26.2/57.7 MB 2.4 MB/s eta 0:00:13
   ------------------ --------------------- 26.7/57.7 MB 2.5 MB/s eta 0:00:13
   ------------------- -------------------- 27.5/57.7 MB 2.5 MB/s eta 0:00:13
   ------------------- -------------------- 28.3/57.7 MB 2.5 MB/s eta 0:00:12
   -------------------- ------------------- 29.4/57.7 MB 2.5 MB/s eta 0:00:12
   -------------------- ------------------- 30.1/57.7 MB 2.6 MB/s eta 0:00:11
   --------------------- ------------------ 30.9/57.7 MB 2.6 MB/s eta 0:00:11
   --------------------- ------------------ 31.5/57.7 MB 2.6 MB/s eta 0:00:11
   ---------------------- ----------------- 32.2/57.7 MB 2.6 MB/s eta 0:00:10
   ----------------------- ---------------- 33.3/57.7 MB 2.6 MB/s eta 0:00:10
   ----------------------- ---------------- 34.1/57.7 MB 2.7 MB/s eta 0:00:09
   ------------------------ --------------- 34.9/57.7 MB 2.7 MB/s eta 0:00:09
   ------------------------ --------------- 35.7/57.7 MB 2.7 MB/s eta 0:00:09
   ------------------------- -------------- 36.7/57.7 MB 2.7 MB/s eta 0:00:08
   ------------------------- -------------- 37.5/57.7 MB 2.8 MB/s eta 0:00:08
   -------------------------- ------------- 38.3/57.7 MB 2.8 MB/s eta 0:00:08
   --------------------------- ------------ 39.3/57.7 MB 2.8 MB/s eta 0:00:07
   --------------------------- ------------ 40.1/57.7 MB 2.8 MB/s eta 0:00:07
   ---------------------------- ----------- 41.2/57.7 MB 2.8 MB/s eta 0:00:06
   ----------------------------- ---------- 41.9/57.7 MB 2.9 MB/s eta 0:00:06
   ----------------------------- ---------- 42.7/57.7 MB 2.9 MB/s eta 0:00:06
   ------------------------------ --------- 43.5/57.7 MB 2.9 MB/s eta 0:00:05
   ------------------------------ --------- 43.8/57.7 MB 2.9 MB/s eta 0:00:05
   ------------------------------ --------- 43.8/57.7 MB 2.9 MB/s eta 0:00:05
   ------------------------------ --------- 43.8/57.7 MB 2.9 MB/s eta 0:00:05
   ------------------------------ --------- 43.8/57.7 MB 2.9 MB/s eta 0:00:05
   ------------------------------- -------- 44.8/57.7 MB 2.8 MB/s eta 0:00:05
   ------------------------------- -------- 45.4/57.7 MB 2.8 MB/s eta 0:00:05
   ------------------------------- -------- 45.9/57.7 MB 2.8 MB/s eta 0:00:05
   -------------------------------- ------- 46.4/57.7 MB 2.8 MB/s eta 0:00:05
   -------------------------------- ------- 46.9/57.7 MB 2.8 MB/s eta 0:00:04
   -------------------------------- ------- 47.4/57.7 MB 2.8 MB/s eta 0:00:04
   --------------------------------- ------ 48.2/57.7 MB 2.8 MB/s eta 0:00:04
   --------------------------------- ------ 49.0/57.7 MB 2.8 MB/s eta 0:00:04
   ---------------------------------- ----- 49.5/57.7 MB 2.8 MB/s eta 0:00:03
   ---------------------------------- ----- 50.3/57.7 MB 2.8 MB/s eta 0:00:03
   ----------------------------------- ---- 51.1/57.7 MB 2.8 MB/s eta 0:00:03
   ----------------------------------- ---- 51.9/57.7 MB 2.8 MB/s eta 0:00:03
   ------------------------------------ --- 52.7/57.7 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 53.7/57.7 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 54.5/57.7 MB 2.9 MB/s eta 0:00:02
   -------------------------------------- - 55.3/57.7 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  56.4/57.7 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  57.1/57.7 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  57.7/57.7 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  57.7/57.7 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 57.7/57.7 MB 2.9 MB/s eta 0:00:00
Downloading gradio_client-1.7.0-py3-none-any.whl (321 kB)
Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Downloading anyio-4.8.0-py3-none-any.whl (96 kB)
Downloading fastapi-0.115.8-py3-none-any.whl (94 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.7-py3-none-any.whl (78 kB)
Using cached MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl (17 kB)
Downloading orjson-3.10.15-cp312-cp312-win_amd64.whl (133 kB)
Downloading pydantic-2.10.6-py3-none-any.whl (431 kB)
Downloading pydantic_core-2.27.2-cp312-cp312-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   --------------------- ------------------ 1.0/2.0 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 1.8/2.0 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 4.3 MB/s eta 0:00:00
Downloading python_multipart-0.0.20-py3-none-any.whl (24 kB)
Downloading ruff-0.9.4-py3-none-win_amd64.whl (10.9 MB)
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
   -- ------------------------------------- 0.8/10.9 MB 3.7 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/10.9 MB 4.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/10.9 MB 3.9 MB/s eta 0:00:03
   ------------ --------------------------- 3.4/10.9 MB 4.2 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/10.9 MB 4.5 MB/s eta 0:00:02
   -------------------- ------------------- 5.5/10.9 MB 4.5 MB/s eta 0:00:02
   ------------------------- -------------- 6.8/10.9 MB 4.7 MB/s eta 0:00:01
   ---------------------------- ----------- 7.9/10.9 MB 4.8 MB/s eta 0:00:01
   ------------------------------- -------- 8.7/10.9 MB 4.8 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/10.9 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  10.7/10.9 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 10.9/10.9 MB 4.7 MB/s eta 0:00:00
Downloading safehttpx-0.1.6-py3-none-any.whl (8.7 kB)
Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading starlette-0.45.3-py3-none-any.whl (71 kB)
Downloading tomlkit-0.13.2-py3-none-any.whl (37 kB)
Downloading typer-0.15.1-py3-none-any.whl (44 kB)
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
Downloading ffmpy-0.5.0-py3-none-any.whl (6.0 kB)
Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading websockets-14.2-cp312-cp312-win_amd64.whl (164 kB)
Installing collected packages: pydub, websockets, tomlkit, sniffio, shellingham, semantic-version, ruff, python-multipart, pydantic-core, orjson, markupsafe, h11, ffmpy, annotated-types, aiofiles, uvicorn, pydantic, httpcore, anyio, typer, starlette, httpx, safehttpx, gradio-client, fastapi, gradio
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.2
    Uninstalling MarkupSafe-3.0.2:
      Successfully uninstalled MarkupSafe-3.0.2
Successfully installed aiofiles-23.2.1 annotated-types-0.7.0 anyio-4.8.0 fastapi-0.115.8 ffmpy-0.5.0 gradio-5.14.0 gradio-client-1.7.0 h11-0.14.0 httpcore-1.0.7 httpx-0.28.1 markupsafe-2.1.5 orjson-3.10.15 pydantic-2.10.6 pydantic-core-2.27.2 pydub-0.25.1 python-multipart-0.0.20 ruff-0.9.4 safehttpx-0.1.6 semantic-version-2.10.0 shellingham-1.5.4 sniffio-1.3.1 starlette-0.45.3 tomlkit-0.13.2 typer-0.15.1 uvicorn-0.34.0 websockets-14.2

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

### **Note**: After this restart the runtime

# **Cleaning Indian Food Recipe Dataset**

In [2]:
# Import libraries

import pandas as pd
import re

In [3]:
# Load the Indian Food dataset
data = pd.read_csv("IndianFoodDataset.csv")

In [4]:
data.head()

,Srno,RecipeName,TranslatedRecipeName,Ingredients,TranslatedIngredients,PrepTimeInMins,CookTimeInMins,TotalTimeInMins,Servings,Cuisine,Course,Diet,Instructions,TranslatedInstructions,URL
0,1,Masala Karela Recipe,Masala Karela Recipe,"6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...","6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...",15,30,45,6,Indian,Side Dish,Diabetic Friendly,"To begin making the Masala Karela Recipe,de-se...","To begin making the Masala Karela Recipe,de-se...",https://www.archanaskitchen.com/masala-karela-...
1,2,टमाटर पुलियोगरे रेसिपी - Spicy Tomato Rice (Re...,Spicy Tomato Rice (Recipe),"2-1/2 कप चावल - पका ले,3 टमाटर,3 छोटा चमच्च बी...","2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...",5,10,15,3,South Indian Recipes,Main Course,Vegetarian,टमाटर पुलियोगरे बनाने के लिए सबसे पहले टमाटर क...,"To make tomato puliogere, first cut the tomato...",http://www.archanaskitchen.com/spicy-tomato-ri...
2,3,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,"1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...","1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...",20,30,50,4,South Indian Recipes,South Indian Breakfast,High Protein Vegetarian,"To begin making the Ragi Vermicelli Recipe, fi...","To begin making the Ragi Vermicelli Recipe, fi...",http://www.archanaskitchen.com/ragi-vermicelli...
3,4,Gongura Chicken Curry Recipe - Andhra Style Go...,Gongura Chicken Curry Recipe - Andhra Style Go...,"500 grams Chicken,2 Onion - chopped,1 Tomato -...","500 grams Chicken,2 Onion - chopped,1 Tomato -...",15,30,45,4,Andhra,Lunch,Non Vegeterian,To begin making Gongura Chicken Curry Recipe f...,To begin making Gongura Chicken Curry Recipe f...,http://www.archanaskitchen.com/gongura-chicken...
4,5,आंध्रा स्टाइल आलम पचड़ी रेसिपी - Adrak Chutney ...,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,"1 बड़ा चमच्च चना दाल,1 बड़ा चमच्च सफ़ेद उरद दाल,2...","1 tablespoon chana dal, 1 tablespoon white ura...",10,20,30,4,Andhra,South Indian Breakfast,Vegetarian,आंध्रा स्टाइल आलम पचड़ी बनाने के लिए सबसे पहले ...,"To make Andhra Style Alam Pachadi, first heat ...",https://www.archanaskitchen.com/andhra-style-a...

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Srno                    1186 non-null   int64
 1   RecipeName              1186 non-null   object
 2   TranslatedRecipeName    1186 non-null   object
 3   Ingredients             1185 non-null   object
 4   TranslatedIngredients   1185 non-null   object
 5   PrepTimeInMins          1186 non-null   int64
 6   CookTimeInMins          1186 non-null   int64
 7   TotalTimeInMins         1186 non-null   int64
 8   Servings                1186 non-null   int64
 9   Cuisine                 1186 non-null   object
 10  Course                  1186 non-null   object
 11  Diet                    1186 non-null   object
 12  Instructions            1186 non-null   object
 13  TranslatedInstructions  1186 non-null   object
 14  URL                     1186 non-null   object
dtypes: int64(5), object(10)
memory usage: 139.1+ KB

In [6]:
# Drop specified columns
data = data.drop(['Srno', 'RecipeName', 'Ingredients', 'Instructions'], axis=1)

In [7]:
data.head()

,TranslatedRecipeName,TranslatedIngredients,PrepTimeInMins,CookTimeInMins,TotalTimeInMins,Servings,Cuisine,Course,Diet,TranslatedInstructions,URL
0,Masala Karela Recipe,"6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...",15,30,45,6,Indian,Side Dish,Diabetic Friendly,"To begin making the Masala Karela Recipe,de-se...",https://www.archanaskitchen.com/masala-karela-...
1,Spicy Tomato Rice (Recipe),"2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...",5,10,15,3,South Indian Recipes,Main Course,Vegetarian,"To make tomato puliogere, first cut the tomato...",http://www.archanaskitchen.com/spicy-tomato-ri...
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,"1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...",20,30,50,4,South Indian Recipes,South Indian Breakfast,High Protein Vegetarian,"To begin making the Ragi Vermicelli Recipe, fi...",http://www.archanaskitchen.com/ragi-vermicelli...
3,Gongura Chicken Curry Recipe - Andhra Style Go...,"500 grams Chicken,2 Onion - chopped,1 Tomato -...",15,30,45,4,Andhra,Lunch,Non Vegeterian,To begin making Gongura Chicken Curry Recipe f...,http://www.archanaskitchen.com/gongura-chicken...
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,"1 tablespoon chana dal, 1 tablespoon white ura...",10,20,30,4,Andhra,South Indian Breakfast,Vegetarian,"To make Andhra Style Alam Pachadi, first heat ...",https://www.archanaskitchen.com/andhra-style-a...

In [8]:
data.isnull().sum()

TranslatedRecipeName      0
TranslatedIngredients     1
PrepTimeInMins            0
CookTimeInMins            0
TotalTimeInMins           0
Servings                  0
Cuisine                   0
Course                    0
Diet                      0
TranslatedInstructions    0
URL                       0
dtype: int64

In [9]:
# Drop rows with missing values
data = data.dropna()

In [10]:
def clean_text(text):
    # Remove non-alphanumeric characters and extra whitespaces
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Apply text cleaning to relevant columns
text_columns = ['TranslatedRecipeName', 'TranslatedIngredients', 'TranslatedInstructions']
for column in text_columns:
    data[column] = data[column].apply(clean_text)

In [11]:
# Save the cleaned dataset
data.to_csv("cleaned_IndianFoodDataset.csv", index=False)

In [15]:
!pip install tf-keras

Collecting tf-keras
  Downloading tf_keras-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: tensorflow<2.19,>=2.18 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tf-keras) (2.18.0)
Requirement already satisfied: tensorflow-intel==2.18.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow<2.19,>=2.18->tf-keras) (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (25.1.24)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (3.4.0)
Requirement already satisfied: packaging in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (2.32.3)
Requirement already satisfied: setuptools in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (75.8.0)
Requirement already satisfied: six>=1.12.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (1.70.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (3.8.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (3.12.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (0.45.1)
Requirement already satisfied: rich in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (13.9.4)
Requirement already satisfied: namex in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (0.0.8)
Requirement already satisfied: optree in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (0.14.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (2024.12.14)
Requirement already satisfied: markdown>=2.6.8 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow<2.19,>=2.18->tf-keras) (0.1.2)
Downloading tf_keras-2.18.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------------ --------------- 1.0/1.7 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 5.2 MB/s eta 0:00:00
Installing collected packages: tf-keras
Successfully installed tf-keras-2.18.0

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
!pip install transformers

Collecting transformers
  Downloading transformers-4.48.2-py3-none-any.whl.metadata (44 kB)
Requirement already satisfied: filelock in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from transformers) (0.28.1)
Requirement already satisfied: numpy>=1.17 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from transformers) (2.32.3)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.0-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from transformers) (0.5.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (2024.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)
Requirement already satisfied: colorama in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\va185069\downloads\bia_notes\tut\lib\site-packages (from requests->transformers) (2024.12.14)
Downloading transformers-4.48.2-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 5.6 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.7 MB 5.6 MB/s eta 0:00:02
   -------------- ------------------------- 3.4/9.7 MB 5.9 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.7 MB 7.1 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.7 MB 7.3 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.7 MB 7.3 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 5.5 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.7 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.7 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 4.9 MB/s eta 0:00:00
Downloading tokenizers-0.21.0-cp39-abi3-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ------------- -------------------------- 0.8/2.4 MB 4.2 MB/s eta 0:00:01
   ------------- -------------------------- 0.8/2.4 MB 4.2 MB/s eta 0:00:01
   ------------- -------------------------- 0.8/2.4 MB 4.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.6/2.4 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  2.4/2.4 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 2.1 MB/s eta 0:00:00
Installing collected packages: tokenizers, transformers
Successfully installed tokenizers-0.21.0 transformers-4.48.2

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

# **Training GPT2 Model on cleaned_IndianFoodDataset**

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import GPT2LMHeadModel, GPT2Tokenizer, TextDataset, DataCollatorForLanguageModeling, Trainer, TrainingArguments

WARNING:tensorflow:From c:\Users\va185069\Downloads\BIA_Notes\tut\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [17]:
# Load the cleaned dataset

data = pd.read_csv("cleaned_IndianFoodDataset.csv")

In [18]:
# Split the dataset into train, validation, and test sets

train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)
train_data, validation_data = train_test_split(train_data, test_size=0.1, random_state=42)

In [19]:
# Save the split datasets

train_data.to_csv("train_dataset.csv", index=False)
validation_data.to_csv("validation_dataset.csv", index=False)
test_data.to_csv("test_dataset.csv", index=False)

In [20]:
# Load the GPT-2 tokenizer and model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2')

SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))"), '(Request ID: 8d45c9d5-f1fe-463e-a7ff-67308943c4d0)')

In [17]:
# Tokenize the datasets
train_dataset = TextDataset(
    tokenizer=tokenizer,
    file_path="train_dataset.csv",
    block_size=128
)

validation_dataset = TextDataset(
    tokenizer=tokenizer,
    file_path="validation_dataset.csv",
    block_size=128
)

test_dataset = TextDataset(
    tokenizer=tokenizer,
    file_path="test_dataset.csv",
    block_size=128
)

/usr/local/lib/python3.10/dist-packages/transformers/data/datasets/language_modeling.py:53: FutureWarning: This dataset will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py
  warnings.warn(

In [18]:
# Set up training arguments
training_args = TrainingArguments(
    output_dir="./gpt2-indian-food",
    overwrite_output_dir=True,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    save_steps=10_000,
    save_total_limit=2,
    prediction_loss_only=True,
)

In [19]:
# Set up trainer
trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False
    ),
    train_dataset=train_dataset,
    eval_dataset=validation_dataset,
)

In [20]:
# Start training

trainer.train()

TrainOutput(global_step=3717, training_loss=2.4297007513777493, metrics={'train_runtime': 444.6408, 'train_samples_per_second': 16.719, 'train_steps_per_second': 8.36, 'total_flos': 485611241472000.0, 'train_loss': 2.4297007513777493, 'epoch': 3.0})

In [27]:
# Save the model

trainer.save_model("gpt2-indian-food")

# Save the configuration file
model = trainer.model
model.config.save_pretrained("gpt2-indian-food_config.json")

In [28]:
# Evaluate on the test set

results = trainer.evaluate(test_dataset)
print(results)

{'eval_loss': 2.325134754180908, 'eval_runtime': 7.1904, 'eval_samples_per_second': 95.266, 'eval_steps_per_second': 11.96, 'epoch': 3.0}

# **Model Evalution - BLUE & ROUGE**

In [1]:
import nltk
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

# Download NLTK resources
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [5]:
# Load the trained model and tokenizer
model = GPT2LMHeadModel.from_pretrained("gpt2-indian-food")
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

# Function to generate text using the model
def generate_text(prompt, max_length=100, temperature=1.0):
    input_ids = tokenizer.encode(prompt, return_tensors="pt")
    output = model.generate(input_ids, max_length=max_length, temperature=temperature, num_beams=5, no_repeat_ngram_size=2)
    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    return generated_text

# Example prompts and references
prompts = ["To make Masala Karela,",
           "Tomato Puliogere is prepared by",
           "Ragi Vermicelli Recipe starts with",
           "Gongura Chicken Curry Recipe first prep all the ingredients",
           "Andhra Style Alam Pachadi is made by"]

references = ["To begin making the Masala Karela Recipe, de-seed the karela and slice.",
              "To make tomato puliogere, first cut the tomatoes.",
              "To begin making the Ragi Vermicelli Recipe, first steam the ragi vermicelli.",
              "To begin making Gongura Chicken Curry Recipe, first prep all the ingredients.",
              "To make Andhra Style Alam Pachadi, first heat oil in a pan."]

# Generate text and calculate BLEU and ROUGE scores
smooth = SmoothingFunction().method1  # Define smoothing function for BLEU
bleu_scores = []
rouge_scores = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

for prompt, reference in zip(prompts, references):
    generated_text = generate_text(prompt)

    # BLEU score
    bleu_score = sentence_bleu([reference.split()], generated_text.split(), smoothing_function=smooth)
    bleu_scores.append(bleu_score)
    print(f"Prompt: {prompt}\nGenerated: {generated_text}\nReference: {reference}\nBLEU Score: {bleu_score:.4f}\n")

    # ROUGE scores
    rouge_score = rouge_scores.score(generated_text, reference)
    print(f"ROUGE Scores: {rouge_score}\n")

# Average BLEU score
average_bleu = sum(bleu_scores) / len(bleu_scores)
print(f"Average BLEU Score: {average_bleu:.4f}")

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: To make Masala Karela,
Generated: To make Masala Karela,Heat oil in a heavy bottomed pan Add mustard seeds urad dal and let it splutterAdd cumin seeds and allow it to crackleAdd ginger garlic paste and saute till the raw smell goes awayAdd turmeric powder red chilli powder coriander powder garam masala powder and salt to taste Mix well and cook for 2 to 3 minutes on medium heatOnce done turn off the heat and transfer to a serving bowl and serve hotServe
Reference: To begin making the Masala Karela Recipe, de-seed the karela and slice.
BLEU Score: 0.0035

ROUGE Scores: {'rouge1': Score(precision=0.6153846153846154, recall=0.10256410256410256, fmeasure=0.17582417582417584), 'rouge2': Score(precision=0.08333333333333333, recall=0.012987012987012988, fmeasure=0.02247191011235955), 'rougeL': Score(precision=0.5384615384615384, recall=0.08974358974358974, fmeasure=0.15384615384615383)}

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: Tomato Puliogere is prepared by
Generated: Tomato Puliogere is prepared by combining all the ingredients mentioned in the list and keep it asideHeat oil in a heavy bottomed pan add mustard seeds and allow it to crackleOnce it crackles add the curry leaves and let it splutterAdd the chopped tomatoes and saute for a few seconds until the tomatoes become soft and mushyOnce done turn off the heat and garnish with green coriander and serve hotServe the Kerala Style Puli Ki Sabzi Recipe along with
Reference: To make tomato puliogere, first cut the tomatoes.
BLEU Score: 0.0023

ROUGE Scores: {'rouge1': Score(precision=0.625, recall=0.06329113924050633, fmeasure=0.1149425287356322), 'rouge2': Score(precision=0.2857142857142857, recall=0.02564102564102564, fmeasure=0.04705882352941176), 'rougeL': Score(precision=0.5, recall=0.05063291139240506, fmeasure=0.09195402298850573)}

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: Ragi Vermicelli Recipe starts with
Generated: Ragi Vermicelli Recipe starts with making the doughIn a mixing bowl combine all the ingredients mentioned in the list and keep it asideHeat oil in a heavy bottomed pan add mustard seeds and allow it to crackleOnce it crackles add the chopped onions and saute till they turn translucentOnce the onions are translucent add chopped tomatoes and cook till the tomatoes become soft and mushyAdd the grated cheese and mix well to combineOnce done turn off the gas and transfer to a serving bowl
Reference: To begin making the Ragi Vermicelli Recipe, first steam the ragi vermicelli.
BLEU Score: 0.0068

ROUGE Scores: {'rouge1': Score(precision=0.5833333333333334, recall=0.08333333333333333, fmeasure=0.14583333333333331), 'rouge2': Score(precision=0.2727272727272727, recall=0.03614457831325301, fmeasure=0.06382978723404255), 'rougeL': Score(precision=0.3333333333333333, recall=0.047619047619047616, fmeasure=0.08333333333333333)}

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Prompt: Gongura Chicken Curry Recipe first prep all the ingredients
Generated: Gongura Chicken Curry Recipe first prep all the ingredients and keep them readyHeat oil in a heavy bottomed pan add mustard seeds cumin seeds and let it splutterAdd onion ginger garlic paste and saute for a few secondsAdd curry leaves and cook till the onion becomes soft and translucentOnce the onions are soft add turmeric powder red chilli powder coriander powder garam masala powder salt and mix wellAdd chicken pieces to the pan and cover it with a lid Cook until the chicken
Reference: To begin making Gongura Chicken Curry Recipe, first prep all the ingredients.
BLEU Score: 0.0393

ROUGE Scores: {'rouge1': Score(precision=0.8333333333333334, recall=0.12048192771084337, fmeasure=0.21052631578947367), 'rouge2': Score(precision=0.7272727272727273, recall=0.0975609756097561, fmeasure=0.17204301075268819), 'rougeL': Score(precision=0.75, recall=0.10843373493975904, fmeasure=0.1894736842105263)}

Prompt: Andhra Style Alam Pachadi is made by
Generated: Andhra Style Alam Pachadi is made by mixing all the ingredients mentioned in the list and keep it asideHeat oil in a heavy bottomed pan Add mustard seeds and let it splutterAdd curry leaves and saute for a few secondsAdd red chilli powder turmeric powder coriander powder garam masala powder and salt to taste Mix well and cook for 2 to 3 minutes until the masalas are well coated with the spicesOnce done turn off the heat and garnish with cor
Reference: To make Andhra Style Alam Pachadi, first heat oil in a pan.
BLEU Score: 0.0194

ROUGE Scores: {'rouge1': Score(precision=0.8333333333333334, recall=0.12345679012345678, fmeasure=0.21505376344086022), 'rouge2': Score(precision=0.45454545454545453, recall=0.0625, fmeasure=0.10989010989010987), 'rougeL': Score(precision=0.6666666666666666, recall=0.09876543209876543, fmeasure=0.17204301075268816)}

Average BLEU Score: 0.0143

# **Checking Model performace with Gradio Interface**

In [6]:
import gradio as gr
from transformers import GPT2LMHeadModel, GPT2Tokenizer

In [7]:
# Load the GPT-2 tokenizer and model
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2-indian-food")  # Use the path where your model is saved

In [8]:
def generate_text(prompt):
    input_ids = tokenizer.encode(prompt, return_tensors="pt")
    output = model.generate(input_ids, max_length=50, num_beams=5, no_repeat_ngram_size=2, top_k=50, top_p=0.95, temperature=0.7)
    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    return generated_text

In [9]:
# Create a Gradio Interface
iface = gr.Interface(
    fn=generate_text,
    inputs="text",
    outputs="text",
    live=True,
    examples=[["To make a delicious curry, ", "you need to start with fresh vegetables and aromatic spices."]]
)

In [10]:
iface.launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://e2aa7d1ba2b6e5a221.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)